; This file was auto-generated by drush_make

api = 2
core = 7.x

projects[drupal][version] = "7.27"
projects[drupal][type] = "core"

; Modules
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta5"
projects[addressfield][type] = "project"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"
projects[admin_menu][type] = "project"

projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"
projects[auto_nodetitle][type] = "project"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.8"
projects[backup_migrate][type] = "project"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"
projects[ctools][type] = "project"

projects[colorbox][subdir] = "contrib"
projects[colorbox][version] = "1.6"
projects[colorbox][type] = "project"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.9"
projects[commerce][type] = "project"

projects[commerce_extra_panes][subdir] = "contrib"
projects[commerce_extra_panes][version] = "1.1"
projects[commerce_extra_panes][type] = "project"

projects[commerce_paypal][subdir] = "contrib"
projects[commerce_paypal][version] = "2.3"
projects[commerce_paypal][type] = "project"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"
projects[content_access][type] = "project"

projects[custom_formatters][subdir] = "contrib"
projects[custom_formatters][version] = "2.2"
projects[custom_formatters][type] = "project"

projects[date][subdir] = "contrib"
projects[date][version] = "2.7"
projects[date][type] = "project"

projects[ds][subdir] = "contrib"
projects[ds][version] = "1.9"
projects[ds][type] = "project"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"
projects[entity][type] = "project"

projects[extlink][subdir] = "contrib"
projects[extlink][version] = "1.16"
projects[extlink][type] = "project"

projects[faq][subdir] = "contrib"
projects[faq][version] = "1.0-rc2"
projects[faq][type] = "project"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"
projects[features][type] = "project"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"
projects[field_permissions][type] = "project"

projects[fullcalendar][subdir] = "contrib"
projects[fullcalendar][version] = "2.0"
projects[fullcalendar][type] = "project"

projects[google_fonts][subdir] = "contrib"
projects[google_fonts][version] = "2.3"
projects[google_fonts][type] = "project"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.4"
projects[google_analytics][type] = "project"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"
projects[libraries][type] = "project"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.3"
projects[logintoboggan][type] = "project"

projects[media][subdir] = "contrib"
projects[media][version] = "1.4"
projects[media][type] = "project"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "1.0-beta3"
projects[media_youtube][type] = "project"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.8"
projects[module_filter][type] = "project"

projects[mollom][subdir] = "contrib"
projects[mollom][version] = "2.9"
projects[mollom][type] = "project"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"
projects[references][type] = "project"

projects[role_delegation][subdir] = "contrib"
projects[role_delegation][version] = "1.1"
projects[role_delegation][type] = "project"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"
projects[panels][type] = "project"

projects[prepopulate][subdir] = "contrib"
projects[prepopulate][version] = "2.x-dev"
projects[prepopulate][type] = "project"

projects[rb][subdir] = "contrib"
projects[rb][version] = "1.x-dev"
projects[rb][type] = "project"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.6"
projects[rules][type] = "project"

projects[signup][subdir] = "contrib"
projects[signup][version] = "1.x-dev"
projects[signup][type] = "project"

projects[signup_rules][subdir] = "contrib"
projects[signup_rules][version] = "1.0-beta1"
projects[signup_rules][type] = "project"

projects[styles][subdir] = "contrib"
projects[styles][version] = "2.0-alpha8"
projects[styles][type] = "project"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"
projects[token][type] = "project"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta7"
projects[video_embed_field][type] = "project"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"
projects[views][type] = "project"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"
projects[views_bulk_operations][type] = "project"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.1"
projects[views_slideshow][type] = "project"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.20"
projects[webform][type] = "project"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"
projects[wysiwyg][type] = "project"

projects[fullcalendar_colors_extension][subdir] = "contrib"
projects[fullcalendar_colors_extension][download][type] = "git"
projects[fullcalendar_colors_extension][download][url] = "http://git.drupal.org/sandbox/aspilicious/1175528.git"
projects[fullcalendar_colors_extension][type] = "module"

; Libraries
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.4/ckeditor_3.6.4.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://www.jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[fullcalendar][download][type] = "get"
libraries[fullcalendar][download][url] = "http://arshaw.com/fullcalendar/downloads/fullcalendar-1.5.3.zip"
libraries[fullcalendar][directory_name] = "fullcalendar"
libraries[fullcalendar][type] = "library"

; Themes
projects[tao][version] = "3.1"
projects[tao][type] = "project"

projects[rubik][version] = "4.0"
projects[rubik][type] = "project"
